
package calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01
 * Generated source version: 2.2
 */
@WebService (name = "Calculator", targetNamespace = "http://calculator/")
@XmlSeeAlso ({
		ObjectFactory.class
})
public interface Calculator {


	/**
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult (targetNamespace = "")
	@RequestWrapper (localName = "mul", targetNamespace = "http://calculator/", className = "calculator.Mul")
	@ResponseWrapper (localName = "mulResponse", targetNamespace = "http://calculator/", className = "calculator.MulResponse")
	@Action (input = "http://calculator/Calculator/mulRequest", output = "http://calculator/Calculator/mulResponse")
	public int mul (
			@WebParam (name = "arg0", targetNamespace = "")
					int arg0,
			@WebParam (name = "arg1", targetNamespace = "")
					int arg1);

	/**
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult (targetNamespace = "")
	@RequestWrapper (localName = "sub", targetNamespace = "http://calculator/", className = "calculator.Sub")
	@ResponseWrapper (localName = "subResponse", targetNamespace = "http://calculator/", className = "calculator.SubResponse")
	@Action (input = "http://calculator/Calculator/subRequest", output = "http://calculator/Calculator/subResponse")
	public int sub (
			@WebParam (name = "arg0", targetNamespace = "")
					int arg0,
			@WebParam (name = "arg1", targetNamespace = "")
					int arg1);

	/**
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult (targetNamespace = "")
	@RequestWrapper (localName = "div", targetNamespace = "http://calculator/", className = "calculator.Div")
	@ResponseWrapper (localName = "divResponse", targetNamespace = "http://calculator/", className = "calculator.DivResponse")
	@Action (input = "http://calculator/Calculator/divRequest", output = "http://calculator/Calculator/divResponse")
	public int div (
			@WebParam (name = "arg0", targetNamespace = "")
					int arg0,
			@WebParam (name = "arg1", targetNamespace = "")
					int arg1);

	/**
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult (targetNamespace = "")
	@RequestWrapper (localName = "add", targetNamespace = "http://calculator/", className = "calculator.Add")
	@ResponseWrapper (localName = "addResponse", targetNamespace = "http://calculator/", className = "calculator.AddResponse")
	@Action (input = "http://calculator/Calculator/addRequest", output = "http://calculator/Calculator/addResponse")
	public int add (
			@WebParam (name = "arg0", targetNamespace = "")
					int arg0,
			@WebParam (name = "arg1", targetNamespace = "")
					int arg1);

}
